name: Build, Publish and Deploy

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker and save container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: image:latest
          build-args: |
            COMMIT_SHA=$COMMIT_SHA
          outputs: type=docker,dest=/tmp/image.tar

      - name: Upload Docker container artifact
        uses: actions/upload-artifact@v2
        with:
          name: image
          path: /tmp/image.tar

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment: development
    steps:
      - name: Checkout
        uses: 'actions/checkout@v3'

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: image
          path: /tmp

      - name: Load Docker image
        run: |
          docker load --input /tmp/image.tar
          docker image ls -a

      - name: Tag Docker image
        run: |
          docker tag image:latest gcr.io/${{ secrets.DEVELOPMENT_PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:$GITHUB_SHA

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.DEVELOPMENT_SERVICE_ACCOUNT }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: Login to gcr.io
        run: |-
          gcloud --quiet auth configure-docker
      - name: Push Docker container
        run: |-
          docker push gcr.io/${{ secrets.DEVELOPMENT_PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:$GITHUB_SHA

  deploy:
    needs: publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment: development
    steps:
      - name: Checkout
        uses: 'actions/checkout@v3'

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.DEVELOPMENT_SERVICE_ACCOUNT }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: Deploy Cloud Run service
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          service: '${{ secrets.SERVICE_NAME }}'
          image: 'gcr.io/${{ secrets.DEVELOPMENT_PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:$GITHUB_SHA'
          region: 'eu-west-3'
          env_vars: ''
